micronaut:
  application:
    name: producer

kafka:
  bootstrap:
    servers: 127.0.0.1:9092
  schema:
    registry:
      url: http://localhost:8081
  specific:
    avro:
      reader: true
  producers:
    default:
      key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      use-native-encoding: true

